version: '3'

services:

  db:
    container_name: mariadb
    image: mariadb:latest
    # args:
    #   DB_DATABASE: wordpress
    #   DB_USER: wordpress
    #   DB_USER_PASSWORD: wordpress
    #   DB_ROOT_PASSWORD: wordpress
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - db
    image: wordpress:latest
    env_file:
      - .env
    volumes:
      - wordpress_data::/var/www/html/wordpress
    networks:
      - inception
    restart: always

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
    image: mynginx
    ports:
      - 443:443
    volumes:
      - wordpress_data::/var/www/html/wordpress
    networks:
      - inception
    restart: always

volumes:
  mariadb_data:
    driver: local
    name: mariadb_data
    driver_opts:
      type: none
      device: /home/reina/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    name: wordpress_data
    driver_opts:
      type: none
      device: /home/reina/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge
    name: inception
  