version: '3.7'

services:

  db:
    container_name: mariadb
    init: true
    build:
      context: requirements/mariadb
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_USER_PASSWORD: ${DB_USER_PASSWORD}
        DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    env_file:
      - .env
    image: my_mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    init: true
    build:
      context: requirements/wordpress
      args: 
        PHP_VERSION: ${PHP_VERSION}
    depends_on:
      - db
      - redis
    env_file:
      - .env
    image: my_wordpress
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    restart: always

  nginx:
    container_name: nginx
    init: true
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
    image: my_nginx
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    restart: always


# bonus
  redis:
    container_name: redis
    init: true
    build:
      context: requirements/redis
    image: my_redis
    networks:
      - inception
    restart: always

# volumes
volumes:
  mariadb_data:
    driver: local
    name: mariadb_data
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    name: wordpress_data
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind

# network

networks:
  inception:
    driver: bridge
    name: inception
  
