# .github/workflows/main.yml
name: Norminette
on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  norminette_job:
    runs-on: ubuntu-latest
    name: norminette
    steps:
    - uses: actions/checkout@v2
    - uses: alexandregv/norminette-action@v3
      with:
        flags: '.'
